### ISSUE TITLE
Unable to install pod

### ISSUE THREAD

**Issue by Haidarooz** [P1xelfehler/IntroScreen#1]
<img width="320" alt="screen shot 2019-01-25 at 10 10 34 pm" src="https://user-images.githubusercontent.com/16222465/51742513-18175b80-20ee-11e9-87a5-02edef733c77.png">

**Comment by P1xelfehler** [comment]
Did you do a `pod update` first? Do you use the latest version (1.0.7)?

If you mean the example project, there was a wrong Podfile, I just fixed.
